### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: ReferenceError: deviceUUID is not defined

### ISSUE THREAD

**Issue by thierry13790** [GusMuche/homebridge-zipabox-accessory#1]
Hi GuMuche,

You did a great job and i'm happy to contribute. I found this error which seems not to be handled please can you check ? It happen only after first init, then once starting pooling this error dissapear

`[2020-1-1 17:53:32] [zipato temperature jardin] Error on connectBox :  ReferenceError: deviceUUID is not defined
    at ZipaAccessory.connectSecurityIfNeeded (/usr/lib/node_modules/homebridge-zipabox-accessory/index.js:208:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

(node:16428) UnhandledPromiseRejectionWarning: Error: ReferenceError: deviceUUID is not defined
    at ZipaAccessory.manageError (/usr/lib/node_modules/homebridge-zipabox-accessory/index.js:213:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:16428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
`

**Comment by thierry13790** [comment]
solved new commit to come soon

**Comment by thierry13790** [comment]
solution published

**Comment by GusMuche** [comment]
Hi. I comme recently but of my vacation, so back online...
You can also try to use the "noStatus" parameter to avoid this error. Be also sure to give the lowest level UUID for your device. In fact the plugin need an attribute UUID as parameter. You can also test this UUID in the Zipato API with the attributes request.
