### ISSUE TITLE
Mode Switch : it set to on device, but refresh problem on Apple Home application

### ISSUE THREAD

**Issue by thierry13790** [GusMuche/homebridge-zipabox-accessory#3]
Application is able to switch on device , also on Apple Home application it set to ON : OK but after a while Apple Home refresh to off device but it stays on as status inside homebridge-zipabox-accessory

Please find some logs :

> [2020-1-1 18:21:53] [Maison Mode economie] calling getOnCharacteristicHandler
[2020-1-1 18:21:53] [Maison Mode economie] Forced refresh after (seconds): 20000
[2020-1-1 18:21:53] [Maison Mode economie] Test Value in manage Status :  true
[2020-1-1 18:21:53] [Maison Mode economie] Methode getAttributesValue()
[2020-1-1 18:21:53] [Maison Mode economie] getAttributesValue request :  https://my.zipato.com:443/zipato-web/v2/attributes/03be33c0-d479-4608-9afe-44fee58853e8/value
In fstatus 200
Response of getAttributesValue : 03be33c0-d479-4608-9afe-44fee58853e8
Response : true
[2020-1-1 18:21:53] [Maison Mode economie] Accessory Value returned by callback: true

So we can see device is ON : True

But device switch to off after a while on apple home 

![pb](https://user-images.githubusercontent.com/21205587/71644200-c3e50600-2cc4-11ea-80d8-3ac657fed2c1.jpg)

**Comment by thierry13790** [comment]
in fact once noStatus=false inside getDeviceStatus is called returnDeviceStatus(jsonResponse)
the uuid to use is the one for device and not the one which is use for reading values i guess. 

If using the uuid from device then we can read status : 

Exemple :

> Request URL
https://my.zipato.com:443/zipato-web/v2/devices/a3193606-9179-4436-8f58-989a9d5bd7c7/status
Response Body
{
  "raw": {
    "transactionId": "5680b52d-5790-4707-9aae-4031a543f29b",
    "device": "a3193606-9179-4436-8f58-989a9d5bd7c7",
    "trouble": false,
    "receiveTimestamp": 1577812128993,
    "batteryTimestamp": 0,
    "batteryLevel": 0,
    "sentTimestamp": 0,
    "onlineState": "INTERNAL",
    "mainsPower": false,
    "online": true
  },
  "online": true,
  "trouble": false,
  "receiveTimestamp": "2019-12-31T17:08:48Z",
  "transactionId": "5680b52d-5790-4707-9aae-4031a543f29b",
  "onlineState": "INTERNAL",
  "timestamp": "2020-01-01T15:26:14Z",
  "batteryLevel": 0,

**Comment by thierry13790** [comment]
Root cause identified : we should send attributes value and not device status

**Comment by thierry13790** [comment]
Problem solved i will add solution through a new commit soon

**Comment by thierry13790** [comment]
Problem solved by modification inside getOnCharacteristicHandler 
In fact if (returnedValue == true) was never true... 

> if(returnedValue == "true"){
			 this.debug && this.log("true");
             callback(error,true);
           }else{
			 this.debug && this.log("false");
             callback(error,false);
           }

**Comment by GusMuche** [comment]
I've try to understand your problem and solution but I can't unterstand the link between a bad status return and the returnedValue==true in getOnCharacteristicHandler.
This if block is only use to reverse the status (to have a false if API send true and true if API send false)...
I'll maybe see more inside your code.
