### ISSUE TITLE
Error: Bad Request

### ISSUE THREAD

**Issue by davidelolli** [GusMuche/homebridge-zipabox-accessory#4]
Goodmorning Gus, 
thanks so much for this project, Zipato needs your help :D 

I've started using yesterday your repo, iv'e configured all accessories one by one with the remote ip (opening target port 8080).
And for the first 3 devices the service run perfectly, but now with around 10 devices I can't have all responding. Every time I restart the homebridge service, random devices starts not responding and other starts going well.
here is a screenshot of my problem:
![Schermata 2020-01-02 alle 22 37 24](https://user-images.githubusercontent.com/59455535/71695281-e86adc00-2db1-11ea-8f4d-056acc410a01.png)

I hope some one can help me, thanks so much.

**Comment by GusMuche** [comment]
Hello Davidelolli,
I think that Zipato have made some restriction to avoid to much connection to the API.
The actual implementation of the plugin create one new connection for each device. Maybe it'll be ok for more than 3 devices in local connection, but seem's that's clearly not the case for more than 3 in remote connection.
I suggest you to test it in local mode (the remote mode is actually not fully implemented, just foreseen).
I've planned to work on a platform implementation after the configuration of all the needed accessory one by one. Then we'll have one connection (two for the security system) for all the devices.
